<div class="right-section">
  {% if site.logo %}
    <a href="{{ "/" | absolute_url }}"><img src="{{ site.logo | relative_url }}" alt="{{ site.title | escape }}" /></a>
  {% endif %}
  <h1><a href="{{ "/" | absolute_url }}">{{ site.title | escape }}</a></h1>
  {% if site.description %}
    <p>{{ site.description }}</p>
  {% endif %}

  {% if site.education %}
    <h3>Education</h3>
    {% for education in site.education %}
      <p><strong>{{ education.degree }}</strong><br>
      {{ education.school }}</p>
      
      <h4>Key Modules:</h4>
      <ul style="list-style: none; padding-left: 0;">
        {% for module in education.key_modules %}
          <li><a href="{{ module.link }}">{{ module.name }}</a></li>
        {% endfor %}
      </ul>
    {% endfor %}

    {% if site.certifications %}
      <h4>Certifications:</h4>
      <ul style="list-style: none; padding-left: 0;">
        {% for cert in site.certifications %}
          <li>{{ cert.name }} - {{ cert.provider }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  {% endif %}

  {% if site.technical_skills %}
    <h3>Technical Skills</h3>
    
    {% if site.technical_skills.programming %}
      <h4>Programming:</h4>
      <p style="font-size: 0.9em;">{{ site.technical_skills.programming | join: ", " }}</p>
    {% endif %}

    {% if site.technical_skills.libraries %}
      <h4>Libraries:</h4>
      <p style="font-size: 0.9em;">{{ site.technical_skills.libraries | join: ", " }}</p>
    {% endif %}

    {% if site.technical_skills.tools %}
      <h4>Tools:</h4>
      <p style="font-size: 0.9em;">{{ site.technical_skills.tools | join: ", " }}</p>
    {% endif %}
  {% endif %}
</div>
