theme: jekyll-theme-minimal
sass:
  style: Compressed
  
title: Tom M

left_content: |
  # Left Section Content
  This is the content for the left section.

right_content: |
  # Right Section Content
  This is the content for the right section.

