title: Tom M
logo: #
description: >
  <a href="https://www.linkedin.com/in/tom-m-498659333">
    <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=flat&logo=linkedin&logoColor=white" alt="LinkedIn">
  </a>

  <a href="https://github.com/GHtjm">
    <img src="https://img.shields.io/badge/GitHub-%23121011.svg?logo=github&logoColor=white" alt="GitHub">
  </a>
  
  <br>
  I graduated from Aberystwyth University in 2021 with a degree in Mathematics, kick starting my professional career in a banking graduate scheme before pursuing a career in data science and landing my first internship at a local agricultural business as a business analyst, learning key business principles while working directly with the company director, applying and developing my analytical skills.
  <br><br>
  I'm a life long student of Mathematics with keen interests in data driven solutions and scientific problem solving.
  <br><br>
  
  <h3>Education</h3>
  <p><strong>BSc Mathematics 2:1</strong><br>
  Aberystwyth University</p>
  
  <h4>Key Modules:</h4>
  <ul style="list-style: none; padding-left: 0;">
    {% for module in site.education.relevant_modules %}
    <li style="font-size: 0.9em;"><a href="{{ module.link }}">{{ module.name }}</a></li>
    {% endfor %}
  </ul>

  <h4>Certifications:</h4>
  <ul style="list-style: none; padding-left: 0;">
    {% for cert in site.education.certifications %}
    <li style="font-size: 0.9em;">{{ cert }}</li>
    {% endfor %}
  </ul>

  <h3>Technical Skills</h3>
  
  <h4>Programming:</h4>
  <p style="font-size: 0.9em;">{{ site.technical_skills.programming | join: ", " }}</p>
  
  <h4>Libraries:</h4>
  <p style="font-size: 0.9em;">{{ site.technical_skills.libraries | join: ", " }}</p>
  
  <h4>Tools:</h4>
  <p style="font-size: 0.9em;">{{ site.technical_skills.tools | join: ", " }}</p>

theme: jekyll-theme-minimal

education:
  relevant_modules:
    - name: "Applied Statistics"
      link: "https://www.aber.ac.uk/en/modules/deptcurrent/MA26600/AB1/"
    - name: "Distributions and Estimation"
      link: "https://www.aber.ac.uk/en/modules/deptcurrent/MA26010/AB1/"
    - name: "Graphs and Networks"
      link: "https://www.aber.ac.uk/en/modules/deptcurrent/MA32410/AB2/"
    - name: "Linear Algebra"
      link: "https://www.aber.ac.uk/en/modules/deptfuture/MA21410/AB2/"
    - name: "Numerical Analysis"
      link: "https://www.aber.ac.uk/en/modules/deptcurrent/MA25220/"
    - name: "Numerical Solutions of PDEs"
      link: "https://www.aber.ac.uk/en/modules/2021/MA34710/"
    - name: "Probability"
      link: "https://www.aber.ac.uk/en/modules/deptcurrent/MA10310/AB1/"
    - name: "Statistics"
      link: "https://www.aber.ac.uk/en/modules/deptcurrent/MA11310/AB2/"
  
  certifications:
    - "Analyzing and Visualizing Data with Excel - Microsoft"
    - "Machine learning and AI with Python, HarvardX"
    - "The Data Science Method - IBM"

technical_skills:
  programming:
    - "Python"
    - "R"
    - "SQL"
  
  libraries:
    - "NumPy"
    - "Pandas"
    - "seaborn"
    - "Matplotlib"
    - "Keras"
    - "PySpark"
    - "TensorFlow"
    - "SciKit"
    - "SciPy"
    - "randomForest"
    - "AdaBoost"
    - "CatBoost"
    - "XGBoost"
    - "LightGBM"
  
  tools:
    - "Power BI"
    - "Tableau"
    - "Excel"
    - "Access"
    - "Azure"
    - "SQL Server"
