Title: Tom M
logo: #
description: >
  <br>
  I graduated from Aberystwyth University in 2021 with a degree in Mathematics, kick starting my professional career in a banking graduate scheme before pursuing a career in data science and landing my first internship at a local agricultural business as a business analyst, learning key business principles while working directly with the company director, applying and developing my analytical skills.
  <br><br>
  I’m a life long student of Mathematics with keen interests in data driven solutions and scientific problem solving.
  <br><br>

  <a href="https://www.linkedin.com/in/tom-m-498659333">
    <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=flat&logo=linkedin&logoColor=white" alt="LinkedIn">
  </a>
theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'
